name: '${project.name}'
version: '${project.version}'
authors: ${authors}
website: '${project.url}'
main: pl.craftserve.radiation.RadiationPlugin
api-version: '${apiVersion}'
description: Makes world radioactive
depend: ['WorldGuard']

commands:
  radiation:
    description: 'Plugin commands.'
    aliases: ['radiacja']
    permission: 'craftserveradiation.radiation'
    usage: '/radiation <safe <radius>|potion <identifier>>'

permissions:
  craftserveradiation.*:
    description: 'Gives all possible permissions.'
    default: false
    children:
    - 'craftserveradiation.ad'
    - 'craftserveradiation.radiation'
  craftserveradiation.ad:
    description: 'Gives access to print Craftserve advertisement.'
    default: op
  craftserveradiation.radiation:
    description: 'Gives access to the "/radiation" command.'
    default: op
